# Generated by Django 5.1.4 on 2025-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_aboutme_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='cv_link',
            field=models.FileField(default='Not provided', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_image',
            field=models.ImageField(blank=True, default='image/about.png', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_link',
            field=models.URLField(default='Not provided'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
