# Generated by Django 5.1.4 on 2025-01-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_aboutme_name_remove_blog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_link',
            field=models.URLField(blank=True, default='Not provided', null=True),
        ),
    ]
