# Generated by Django 5.1.4 on 2025-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_aboutme_cv_link_alter_aboutme_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cv_link',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
