# Generated by Django 5.1.4 on 2025-01-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_aboutme_cv_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Details about yourself')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of yourself', null=True, upload_to='about/')),
                ('cv', models.FileField(blank=True, help_text='Upload your CV', null=True, upload_to='cv/')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
